import { decrypt } from './cryptoHelpers';

// Test decrypt() with a known-good ciphertext generated by the same KDF + AES-GCM parameters as the production encrypt path.
describe('src/utils/keystore/cryptoHelpers.ts', () => {
  const KEYGEN_ITERATIONS_V2 = 100000;
  const AES_LENGTH = 256;
  const TAG_LENGTH = 128;
  const password = 'correct horse battery staple';
  const plaintext = new TextEncoder().encode('super-secret-private-key');

  // Mirrors the production encrypt path (same KDF + AES-GCM parameters).
  const encrypt = async (
    pass: string,
    data: Uint8Array,
    salt: Uint8Array,
    iv: Uint8Array,
    iterations: number,
  ) => {
    const { sha256 } = await import('@noble/hashes/sha256');
    const { concatBytes, utf8ToBytes } = await import('@noble/hashes/utils');
    const pwkey = sha256(concatBytes(utf8ToBytes(pass), salt));
    const keyMaterial = await crypto.subtle.importKey(
      'raw',
      pwkey,
      { name: 'PBKDF2' },
      false,
      ['deriveKey'],
    );
    const key = await crypto.subtle.deriveKey(
      { name: 'PBKDF2', salt, iterations, hash: 'SHA-256' },
      keyMaterial,
      { name: 'AES-GCM', length: AES_LENGTH },
      false,
      ['encrypt', 'decrypt'],
    );
    return new Uint8Array(
      await crypto.subtle.encrypt(
        { name: 'AES-GCM', iv, additionalData: salt, tagLength: TAG_LENGTH },
        key,
        data,
      ),
    );
  };

  const salt = new Uint8Array(16).fill(3);
  const iv = new Uint8Array(12).fill(7);

  it('decrypts with the correct password', async () => {
    const ciphertext = await encrypt(
      password,
      plaintext,
      salt,
      iv,
      KEYGEN_ITERATIONS_V2,
    );

    const decrypted = await decrypt(
      password,
      ciphertext,
      salt,
      iv,
      KEYGEN_ITERATIONS_V2,
    );

    expect(new TextDecoder().decode(decrypted)).toBe(
      'super-secret-private-key',
    );
  });

  it('throws for a wrong password (AES-GCM auth failure)', async () => {
    const ciphertext = await encrypt(
      password,
      plaintext,
      salt,
      iv,
      KEYGEN_ITERATIONS_V2,
    );

    await expect(
      decrypt('wrong password', ciphertext, salt, iv, KEYGEN_ITERATIONS_V2),
    ).rejects.toBeDefined();
  });

  it('throws for tampered ciphertext', async () => {
    const ciphertext = await encrypt(
      password,
      plaintext,
      salt,
      iv,
      KEYGEN_ITERATIONS_V2,
    );
    ciphertext[0] ^= 0xff;

    await expect(
      decrypt(password, ciphertext, salt, iv, KEYGEN_ITERATIONS_V2),
    ).rejects.toBeDefined();
  });
});
