nodeLinker: node-modules

# https://yarnpkg.com/migration/guide#update-your-configuration-to-the-new-settings
# ignore-scripts true -> enableScripts: false
enableScripts: false

yarnPath: .yarn/releases/yarn-4.6.0.cjs
