import { fixupConfigRules, fixupPluginRules } from '@eslint/compat';
import { FlatCompat } from '@eslint/eslintrc';
import js from '@eslint/js';
import typescriptEslint from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';
import react from 'eslint-plugin-react';
import globals from 'globals';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
  allConfig: js.configs.all,
});

export default [
  ...fixupConfigRules(
    compat.extends(
      'eslint:recommended',
      'plugin:react/recommended',
      'plugin:react/jsx-runtime',
      'plugin:react-hooks/recommended',
      'plugin:@typescript-eslint/recommended',
      'prettier',
      'plugin:prettier/recommended',
    ),
  ),
  {
    plugins: {
      react: fixupPluginRules(react),
      '@typescript-eslint': fixupPluginRules(typescriptEslint),
    },

    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
      },

      parser: tsParser,
      ecmaVersion: 12,
      sourceType: 'module',

      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
    },

    settings: {
      react: {
        pragma: 'React',
        version: 'detect',
      },
    },

    rules: {
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      'react/prop-types': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-var-requires': 'off',
      'no-shadow': 'off',
      '@typescript-eslint/no-shadow': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          args: 'all',
          argsIgnorePattern: '^_',
          caughtErrors: 'all',
          caughtErrorsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          ignoreRestSiblings: true,
        },
      ],
    },
  },
  {
    // ignoring files generated by @hey-api
    ignores: ['**/*.gen.ts'],
  },
  {
    files: ['packages/lavamoat-rspack/**/*.{js,ts,mjs,cjs}'],
    rules: {
      // Forked LavaMoat plugin uses CommonJS `require` in .js sources
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
  {
    // `truncateAddress` returns a shortened *string*, so the characters it
    // drops leave the DOM entirely and no amount of selecting, copying or
    // inspecting brings them back. Rendering one without also offering the
    // full value is how an address the user cannot verify ends up on an
    // approval screen. `<TruncatedAddress />` pairs the two; use it instead.
    files: ['apps/next/src/**/*.{ts,tsx}'],
    ignores: [
      // Defines the component, and AddressItem pairs truncation with its own
      // tooltip plus a copy button.
      'apps/next/src/components/Address/**',
      // Not an address render: builds a display *symbol* for an unknown token.
      'apps/next/src/pages/Fusion/hooks/useRecurringSwapOrders.ts',
    ],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: '@avalabs/k2-alpine',
              importNames: ['truncateAddress'],
              message:
                'Use <TruncatedAddress /> from @/components/Address so the full address stays reachable on hover.',
            },
            {
              name: '@core/common',
              importNames: ['truncateAddress'],
              message:
                'Use <TruncatedAddress /> from @/components/Address so the full address stays reachable on hover.',
            },
          ],
        },
      ],
    },
  },
];
