// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  GetV1BalanceGetSupportedChainsData,
  GetV1BalanceGetSupportedChainsResponses,
  PostV1BalanceGetBalancesData,
  PostV1BalanceGetBalancesErrors,
  PostV1BalanceGetBalancesResponses,
  PostV1StakeGetRewardsData,
  PostV1StakeGetRewardsResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const postV1BalanceGetBalances = <ThrowOnError extends boolean = false>(
  options: Options<PostV1BalanceGetBalancesData, ThrowOnError>,
) => {
  return (options.client ?? client).sse.post<
    PostV1BalanceGetBalancesResponses,
    PostV1BalanceGetBalancesErrors,
    ThrowOnError
  >({
    security: [
      {
        name: 'x-firebase-appcheck',
        type: 'apiKey',
      },
    ],
    url: '/v1/balance/get-balances',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const getV1BalanceGetSupportedChains = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetV1BalanceGetSupportedChainsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetV1BalanceGetSupportedChainsResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        name: 'x-firebase-appcheck',
        type: 'apiKey',
      },
    ],
    url: '/v1/balance/get-supported-chains',
    ...options,
  });
};

export const postV1StakeGetRewards = <ThrowOnError extends boolean = false>(
  options: Options<PostV1StakeGetRewardsData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostV1StakeGetRewardsResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        name: 'x-firebase-appcheck',
        type: 'apiKey',
      },
    ],
    url: '/v1/stake/get-rewards',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
