// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'https://core-balance-api.avax.network' | (string & {});
};

/**
 * The request body for the get-balances endpoint
 */
export type GetBalancesRequestBody = {
  data: Array<
    | {
        /**
         * The caip2 namespace
         */
        namespace: string;
        /**
         * The addresses we want to get and sum up the balances for
         */
        addresses: Array<string>;
        /**
         * The second part for the caip2 chain ID
         */
        references: Array<string>;
      }
    | {
        /**
         * The caip2 namespace for Avalanche chains
         */
        namespace: 'avax';
        /**
         * The second part for the caip2 chain ID
         */
        references: Array<
          | '11111111111111111111111111111111LpoYY'
          | 'fuji-11111111111111111111111111111111LpoYY'
          | '2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM'
          | '2JVSBoinj9C2J33VntvzYtVJNZdN2NKiwwKjcumHUWEb5DbBrm'
        >;
        addressDetails: Array<{
          /**
           * The wallet's ID. Will default to the hash of the addresses if not provided.
           */
          walletId?: string;
          /**
           * The addresses we want to get and sum up the balances for
           */
          addresses: Array<string>;
        }>;
      }
    | {
        /**
         * The caip2 namespace for Avalanche chains
         */
        namespace: 'avax';
        /**
         * The second part for the caip2 chain ID
         */
        references: Array<
          | '11111111111111111111111111111111LpoYY'
          | 'fuji-11111111111111111111111111111111LpoYY'
          | '2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM'
          | '2JVSBoinj9C2J33VntvzYtVJNZdN2NKiwwKjcumHUWEb5DbBrm'
        >;
        extendedPublicKeyDetails: Array<{
          /**
           * The wallet's ID. Will default to the hash of the extended public key if not provided.
           */
          walletId?: string;
          /**
           * The extended public key for X / P chain
           */
          extendedPublicKey: string & string;
        }>;
      }
  >;
  currency?: Currency;
};

/**
 * The currency we are using for balance calculation
 */
export type Currency = 'usd' | 'eur' | 'aud' | 'cad' | 'chf';

/**
 * The request body for the get rewards endpoint
 */
export type GetStakeRewardsRequestBody =
  | {
      /**
       * The extended public key for X / P chain
       */
      extendedPublicKey: string & string;
      isTestnet: boolean;
    }
  | {
      addresses: Array<string>;
      isTestnet: boolean;
    };

/**
 * Get balances response
 */
export type GetBalancesResponse =
  | ({
      networkType: 'evm';
    } & EvmGetBalancesResponse)
  | ({
      networkType: 'btc';
    } & BtcGetBalancesResponse)
  | ({
      networkType: 'svm';
    } & SvmGetBalancesResponse)
  | ({
      networkType: 'avm';
    } & AvmGetBalancesResponse)
  | ({
      networkType: 'pvm';
    } & PvmGetBalancesResponse)
  | {
      error: string;
    };

/**
 * The balance response for EVM chains
 */
export type EvmGetBalancesResponse = {
  caip2Id: string;
  networkType: 'evm';
  id: string;
  balances: {
    nativeTokenBalance: NativeTokenBalance;
    /**
     * Total balance in given currency
     */
    totalBalanceInCurrency?: number;
    erc20TokenBalances: Array<Erc20TokenBalance>;
  };
  error: string | null;
};

/**
 * Native Token Balance
 *
 * The balance for the native token
 */
export type NativeTokenBalance = {
  internalId?: string;
  name: string;
  symbol: string;
  type: 'native';
  decimals: number;
  logoUri?: string;
  balance: string;
  balanceInCurrency?: number;
  price?: number;
  priceChange24h?: number;
  priceChangePercentage24h?: number;
};

/**
 * ERC20 Token Balance
 *
 * The balance for a given ERC20 token
 */
export type Erc20TokenBalance = {
  internalId?: string;
  name: string;
  symbol: string;
  type: 'erc20';
  decimals: number;
  logoUri?: string;
  balance: string;
  balanceInCurrency?: number;
  price?: number;
  priceChange24h?: number;
  priceChangePercentage24h?: number;
  address: string;
  scanResult?: 'Benign' | 'Malicious' | 'Warning' | 'Spam';
};

/**
 * The balance response for BTC chains
 */
export type BtcGetBalancesResponse = {
  caip2Id: string;
  networkType: 'btc';
  id: string;
  balances: {
    nativeTokenBalance: {
      internalId?: string;
      name: string;
      symbol: string;
      type: 'native';
      decimals: number;
      logoUri?: string;
      balance: string;
      balanceInCurrency?: number;
      price?: number;
      priceChange24h?: number;
      priceChangePercentage24h?: number;
      unconfirmedBalance: string;
      unconfirmedBalanceInCurrency?: number;
    };
    /**
     * Total balance in given currency
     */
    totalBalanceInCurrency?: number;
  };
  error: string | null;
};

/**
 * The balance response for SVM chains
 */
export type SvmGetBalancesResponse = {
  caip2Id: string;
  networkType: 'svm';
  id: string;
  balances: {
    nativeTokenBalance: NativeTokenBalance;
    /**
     * Total balance in given currency
     */
    totalBalanceInCurrency?: number;
    splTokenBalances: Array<{
      internalId?: string;
      name: string;
      symbol: string;
      type: 'spl';
      decimals: number;
      logoUri?: string;
      balance: string;
      balanceInCurrency?: number;
      price?: number;
      priceChange24h?: number;
      priceChangePercentage24h?: number;
      address: string;
      scanResult?: 'Benign' | 'Malicious' | 'Warning' | 'Spam';
    }>;
  };
  error: string | null;
};

/**
 * The balance response for X-chain
 */
export type AvmGetBalancesResponse = {
  caip2Id: string;
  networkType: 'avm';
  id: string;
  balances: {
    nativeTokenBalance: NativeTokenBalance;
    /**
     * Total balance in given currency
     */
    totalBalanceInCurrency?: number;
    categories: {
      unlocked: Array<AvalancheBalanceItem>;
      locked: Array<AvalancheBalanceItem>;
      atomicMemoryUnlocked: Array<AvalancheBalanceItem>;
      atomicMemoryLocked: Array<AvalancheBalanceItem>;
    };
  };
  error: string | null;
};

/**
 * Avalanche Balance Item
 *
 * The balance for a given Avalanche asset
 */
export type AvalancheBalanceItem = {
  internalId?: string;
  name: string;
  symbol: string;
  type: 'native' | 'unknown';
  decimals: number;
  logoUri?: string;
  balance: string;
  balanceInCurrency?: number;
  price?: number;
  priceChange24h?: number;
  priceChangePercentage24h?: number;
  assetId: string;
};

/**
 * The balance response for P-chain
 */
export type PvmGetBalancesResponse = {
  caip2Id: string;
  networkType: 'pvm';
  id: string;
  balances: {
    nativeTokenBalance: NativeTokenBalance;
    /**
     * Total balance in given currency
     */
    totalBalanceInCurrency?: number;
    categories: {
      unlockedStaked: Array<AvalancheBalanceItem>;
      unlockedUnstaked: Array<AvalancheBalanceItem>;
      lockedStaked: Array<AvalancheBalanceItem>;
      lockedPlatform: Array<AvalancheBalanceItem>;
      lockedStakeable: Array<AvalancheBalanceItem>;
      pendingStaked: Array<AvalancheBalanceItem>;
      atomicMemoryLocked: Array<AvalancheBalanceItem>;
      atomicMemoryUnlocked: Array<AvalancheBalanceItem>;
    };
  };
  error: string | null;
};

/**
 * Get stake rewards response
 */
export type GetStakeRewardsResponse = {
  historicalRewardsAmount: string;
  pendingStakeAmount: string;
  estimatedRewardAmount: string;
};

export type PostV1BalanceGetBalancesData = {
  /**
   * The request body for the get-balances endpoint
   */
  body: GetBalancesRequestBody;
  path?: never;
  query?: never;
  url: '/v1/balance/get-balances';
};

export type PostV1BalanceGetBalancesResponses = {
  /**
   * Default Response
   */
  200: GetBalancesResponse;
};

export type PostV1BalanceGetBalancesResponse =
  PostV1BalanceGetBalancesResponses[keyof PostV1BalanceGetBalancesResponses];

export type PostV1StakeGetRewardsData = {
  /**
   * The request body for the get rewards endpoint
   */
  body: GetStakeRewardsRequestBody;
  path?: never;
  query?: never;
  url: '/v1/stake/get-rewards';
};

export type PostV1StakeGetRewardsResponses = {
  /**
   * Default Response
   */
  200: GetStakeRewardsResponse;
};

export type PostV1StakeGetRewardsResponse =
  PostV1StakeGetRewardsResponses[keyof PostV1StakeGetRewardsResponses];
