// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'https://core-balance-api.avax.network' | (string & {});
};

/**
 * The request body for the get-balances endpoint
 */
export type GetBalancesRequestBody = {
  data: Array<{
    /**
     * The caip2 namespace
     */
    namespace: string;
    /**
     * The addresses we want to get and sum up the balances for
     */
    addresses: Array<string>;
    /**
     * The second part for the caip2 chain ID
     */
    references: Array<string>;
  }>;
  currency?: Currency;
};

/**
 * The currency we are using for balance calculation
 */
export type Currency = 'usd' | 'eur' | 'aud' | 'cad' | 'chf';

/**
 * The request body for the get rewards endpoint
 */
export type GetStakeRewardsRequestBody =
  | {
      /**
       * The extended public key for P-chain
       */
      extendedPublicKey: string & string;
      isTestnet: boolean;
    }
  | {
      addresses: Array<string>;
      isTestnet: boolean;
    };

/**
 * Get balances response
 */
export type GetBalancesResponse =
  | EvmGetBalancesResponse
  | BtcGetBalancesResponse
  | {
      caip2Id: string;
      networkType: 'svm';
      address: string;
      balances: {
        nativeTokenBalance: NativeTokenBalance;
        /**
         * Total balance in given currency
         */
        totalBalanceInCurrency?: number;
        splTokenBalances: Array<{
          internalId?: string;
          name: string;
          symbol: string;
          type: 'spl';
          decimals: number;
          logoUri?: string;
          balance: string;
          balanceInCurrency?: number;
          price?: number;
          priceChange24h?: number;
          priceChangePercentage24h?: number;
          address: string;
          scanResult?: 'Benign' | 'Malicious' | 'Warning' | 'Spam';
        }>;
      };
      error: string | null;
    }
  | {
      error: string;
    };

/**
 * The balance response for EVM chains
 */
export type EvmGetBalancesResponse = {
  caip2Id: string;
  networkType: 'evm';
  address: string;
  balances: {
    nativeTokenBalance: NativeTokenBalance;
    /**
     * Total balance in given currency
     */
    totalBalanceInCurrency?: number;
    erc20TokenBalances: Array<Erc20TokenBalance>;
  };
  error: string | null;
};

/**
 * Native Token Balance
 *
 * The balance for the native token
 */
export type NativeTokenBalance = {
  internalId?: string;
  name: string;
  symbol: string;
  type: 'native';
  decimals: number;
  logoUri?: string;
  balance: string;
  balanceInCurrency?: number;
  price?: number;
  priceChange24h?: number;
  priceChangePercentage24h?: number;
};

/**
 * ERC20 Token Balance
 *
 * The balance for a given ERC20 token
 */
export type Erc20TokenBalance = {
  internalId?: string;
  name: string;
  symbol: string;
  type: 'erc20';
  decimals: number;
  logoUri?: string;
  balance: string;
  balanceInCurrency?: number;
  price?: number;
  priceChange24h?: number;
  priceChangePercentage24h?: number;
  address: string;
  scanResult?: 'Benign' | 'Malicious' | 'Warning' | 'Spam';
};

/**
 * The balance response for BTC chains
 */
export type BtcGetBalancesResponse = {
  caip2Id: string;
  networkType: 'btc';
  address: string;
  balances: {
    nativeTokenBalance: {
      internalId?: string;
      name: string;
      symbol: string;
      type: 'native';
      decimals: number;
      logoUri?: string;
      balance: string;
      balanceInCurrency?: number;
      price?: number;
      priceChange24h?: number;
      priceChangePercentage24h?: number;
      unconfirmedBalance: string;
      unconfirmedBalanceInCurrency?: number;
    };
    /**
     * Total balance in given currency
     */
    totalBalanceInCurrency?: number;
  };
  error: string | null;
};

/**
 * Get stake rewards response
 */
export type GetStakeRewardsResponse = {
  historicalRewardsAmount: string;
  pendingStakeAmount: string;
  estimatedRewardAmount: string;
};

export type PostV1BalanceGetBalancesData = {
  /**
   * The request body for the get-balances endpoint
   */
  body: GetBalancesRequestBody;
  path?: never;
  query?: never;
  url: '/v1/balance/get-balances';
};

export type PostV1BalanceGetBalancesResponses = {
  /**
   * Default Response
   */
  200: GetBalancesResponse;
};

export type PostV1BalanceGetBalancesResponse =
  PostV1BalanceGetBalancesResponses[keyof PostV1BalanceGetBalancesResponses];

export type PostV1StakeGetRewardsData = {
  /**
   * The request body for the get rewards endpoint
   */
  body: GetStakeRewardsRequestBody;
  path?: never;
  query?: never;
  url: '/v1/stake/get-rewards';
};

export type PostV1StakeGetRewardsResponses = {
  /**
   * Default Response
   */
  200: GetStakeRewardsResponse;
};

export type PostV1StakeGetRewardsResponse =
  PostV1StakeGetRewardsResponses[keyof PostV1StakeGetRewardsResponses];
