export enum FeatureGates {
  EVERYTHING = 'everything',
  EVENTS = 'events',
  SWAP = 'swap-feature',
  SWAP_C_CHAIN = 'swap-c-chain',
  SWAP_ETHEREUM = 'swap-ethereum',
  SWAP_SOLANA = 'swap-solana',
  SWAP_FEES = 'swap-fees',
  SWAP_FEES_JUPITER = 'swap-fees-jupiter',
  BRIDGE = 'bridge-feature',
  BRIDGE_ETH = 'bridge-feature-eth',
  BRIDGE_BTC = 'bridge-feature-btc',
  SEND = 'send-feature',
  SEND_P_CHAIN = 'send-p-chain',
  SEND_X_CHAIN = 'send-x-chain',
  SENDTRANSACTION_CHAIN_ID_SUPPORT = 'sendtransaction-chain-id-support-feature',
  BUY = 'buy',
  BUY_MOONPAY = 'buy-feature-moonpay',
  BUY_COINBASE = 'buy-feature-coinbase',
  KEYSTONE = 'keystone',
  KEYSTONE_3 = 'keystone3-onboarding',
  NFT_MARKETPLACE = 'nft-marketplace',
  BOTTOM_NAVIGATION = 'bottom-navigation',
  DEFI = 'defi-feature',
  IMPORT_WALLET_CONNECT = 'import-wallet-connect',
  IMPORT_FIREBLOCKS = 'import-fireblocks',
  IN_APP_SUPPORT_P_CHAIN = 'in-app-support-p-chain',
  IN_APP_SUPPORT_X_CHAIN = 'in-app-support-x-chain',
  SEEDLESS_ONBOARDING = 'seedless-onboarding',
  SEEDLESS_ONBOARDING_GOOGLE = 'seedless-onboarding-google',
  SEEDLESS_ONBOARDING_APPLE = 'seedless-onboarding-apple',
  SEEDLESS_MFA_PASSKEY = 'seedless-mfa-passkey',
  SEEDLESS_MFA_AUTHENTICATOR = 'seedless-mfa-authenticator',
  SEEDLESS_MFA_YUBIKEY = 'seedless-mfa-yubikey',
  SEEDLESS_SIGNING = 'seedless-signing',
  SEEEDLESS_MFA_SETTINGS = 'seedless-mfa-settings',
  SEEDLESS_OPTIONAL_MFA = 'seedless-optional-mfa',
  UNIFIED_BRIDGE_CCTP = 'unified-bridge-cctp',
  UNIFIED_BRIDGE_ICTT = 'unified-bridge-ictt',
  UNIFIED_BRIDGE_AB_EVM = 'unified-bridge-ab-evm',
  UNIFIED_BRIDGE_AB_AVA_TO_BTC = 'unified-bridge-ab-ava-to-btc',
  UNIFIED_BRIDGE_AB_BTC_TO_AVA = 'unified-bridge-ab-btc-to-ava',
  DEBANK_TRANSACTION_PARSING = 'debank-transaction-parsing',
  DEBANK_TRANSACTION_PRE_EXECUTION = 'debank-transaction-pre-execution',
  PRIMARY_ACCOUNT_REMOVAL = 'primary-account-removal',
  ADD_WALLET_WITH_SEEDPHRASE = 'add-wallet-with-seedphrase',
  ADD_WALLET_WITH_KEYSTORE_FILE = 'add-wallet-with-keystore-file',
  ADD_WALLET_WITH_LEDGER = 'add-wallet-with-ledger',
  BLOCKAID_DAPP_SCAN = 'blockaid-dapp-scan',
  BLOCKAID_DAPP_SCAN_WARNING = 'blockaid-dapp-scan-warning',
  BLOCKAID_TRANSACTION_SCAN = 'blockaid-transaction-scan',
  BLOCKAID_JSONRPC_SCAN = 'blockaid-jsonrpc-scan',
  HALLIDAY_BRIDGE_BANNER = 'halliday-bridge-banner',
  FIREBASE_CLOUD_MESSAGING = 'firebase-cloud-messaging',
  ONE_CLICK_SWAP = 'one-click-swap',
  GASLESS = 'gasless',
  SOLANA_SUPPORT = 'solana-support',
  SOLANA_LAUNCH_MODAL = 'solana-launch-modal',
  CORE_ASSISTANT = 'core-assistant',
  SWAP_USE_MARKR = 'swap-use-markr',
  BALANCE_SERVICE_INTEGRATION = 'balance-service-integration',
}

export enum FeatureVars {
  MARKR_SWAP_GAS_BUFFER = 'markr-swap-gas-buffer',
}

export enum FeatureFlagEvents {
  FEATURE_FLAG_UPDATED = 'FeatureFlagEvents: FEATURE_FLAG_UPDATED',
}

export type FeatureFlags = Record<FeatureGates, boolean> &
  Record<FeatureVars, string>;

export type FeatureFlagPayloads = Record<FeatureGates | FeatureVars, string>;
