// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  GetV1TokenlistData,
  GetV1TokenlistResponses,
  GetV1TokensData,
  GetV1TokensResponses,
  GetV1TrendingListData,
  GetV1TrendingListResponses,
  GetV1WatchlistData,
  GetV1WatchlistMarketsData,
  GetV1WatchlistMarketsResponses,
  GetV1WatchlistPriceData,
  GetV1WatchlistPriceResponses,
  GetV1WatchlistResponses,
  GetV1WatchlistTokensData,
  GetV1WatchlistTokensResponses,
  GetV1WatchlistTrendingData,
  GetV1WatchlistTrendingResponses,
  PostV1TokenLookupData,
  PostV1TokenLookupResponses,
  PostV1TokenLookupWithPriceData,
  PostV1TokenLookupWithPriceResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const getV1Tokenlist = <ThrowOnError extends boolean = false>(
  options?: Options<GetV1TokenlistData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetV1TokenlistResponses,
    unknown,
    ThrowOnError
  >({
    url: '/v1/tokenlist',
    ...options,
  });
};

export const getV1Tokens = <ThrowOnError extends boolean = false>(
  options: Options<GetV1TokensData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetV1TokensResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        name: 'x-firebase-appcheck',
        type: 'apiKey',
      },
    ],
    url: '/v1/tokens',
    ...options,
  });
};

export const getV1TrendingList = <ThrowOnError extends boolean = false>(
  options?: Options<GetV1TrendingListData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetV1TrendingListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        name: 'x-firebase-appcheck',
        type: 'apiKey',
      },
    ],
    url: '/v1/trending-list',
    ...options,
  });
};

export const postV1TokenLookup = <ThrowOnError extends boolean = false>(
  options: Options<PostV1TokenLookupData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostV1TokenLookupResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        name: 'x-firebase-appcheck',
        type: 'apiKey',
      },
    ],
    url: '/v1/token/lookup',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const postV1TokenLookupWithPrice = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostV1TokenLookupWithPriceData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostV1TokenLookupWithPriceResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        name: 'x-firebase-appcheck',
        type: 'apiKey',
      },
    ],
    url: '/v1/token/lookup-with-price',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const getV1Watchlist = <ThrowOnError extends boolean = false>(
  options: Options<GetV1WatchlistData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetV1WatchlistResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        name: 'x-firebase-appcheck',
        type: 'apiKey',
      },
    ],
    url: '/v1/watchlist/',
    ...options,
  });
};

export const getV1WatchlistMarkets = <ThrowOnError extends boolean = false>(
  options: Options<GetV1WatchlistMarketsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetV1WatchlistMarketsResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        name: 'x-firebase-appcheck',
        type: 'apiKey',
      },
    ],
    url: '/v1/watchlist/markets',
    ...options,
  });
};

export const getV1WatchlistTokens = <ThrowOnError extends boolean = false>(
  options: Options<GetV1WatchlistTokensData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetV1WatchlistTokensResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        name: 'x-firebase-appcheck',
        type: 'apiKey',
      },
    ],
    url: '/v1/watchlist/tokens',
    ...options,
  });
};

export const getV1WatchlistPrice = <ThrowOnError extends boolean = false>(
  options?: Options<GetV1WatchlistPriceData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetV1WatchlistPriceResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        name: 'x-firebase-appcheck',
        type: 'apiKey',
      },
    ],
    url: '/v1/watchlist/price',
    ...options,
  });
};

export const getV1WatchlistTrending = <ThrowOnError extends boolean = false>(
  options?: Options<GetV1WatchlistTrendingData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetV1WatchlistTrendingResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        name: 'x-firebase-appcheck',
        type: 'apiKey',
      },
    ],
    url: '/v1/watchlist/trending',
    ...options,
  });
};
