// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'https://core-token-aggregator.avax-test.network' | (string & {});
};

export type Caip2IdAddressPair = {
  caip2Id: string;
  address: string;
};

/**
 * Single unique identifier of the token in the token aggregator database
 */
export type InternalId = {
  internalId: string;
};

/**
 * The available currencies: usd, eur, aud, cad, chf, clp, czk, dkk, gbp, hkd, huf, ils, inr
 */
export type Currency = string;

/**
 * Get the list of tokens for each chain
 */
export type TokenListResponse = {
  data: {
    [key: string]: {
      tokens: Array<{
        internalId: string;
        address: string;
        name: string;
        symbol: string;
        isNative: boolean;
        logoUri?: string;
        caip2Id: string;
        contractType: 'ERC-20' | 'SPL';
        chainId: number;
        decimals: number;
        color?: string;
      }>;
    };
  };
};

/**
 * The response for the /tokens endpoint
 */
export type TokensResponse = {
  data: Array<{
    internalId: string;
    address: string;
    name: string;
    symbol: string;
    isNative: boolean;
    logoUri: string | null;
    decimals: number | null;
  }>;
};

/**
 * The response of the trending list endpoint
 */
export type TrendingListResponse = {
  data: Array<{
    internalId: string;
    coingeckoId?: string | null;
    platforms: Platforms;
    isNative: boolean;
    name: string;
    symbol: string;
    scanResult?: ScanResult | null;
    scannedAt?: string | null;
    meta?: TokenMetadata | null;
    rank: number;
    chain: string;
  }>;
};

/**
 * The platforms the token can be found on
 */
export type Platforms = {
  [key: string]: string;
} | null;

/**
 * The scan result from Blockaid
 */
export type ScanResult = 'Benign' | 'Warning' | 'Malicious' | 'Spam';

/**
 * The token metadata
 */
export type TokenMetadata = {
  logoUri: string | null;
  decimals: Decimals | null;
};

/**
 * The decimals on the different chains
 */
export type Decimals = {
  [key: string]: number | null;
};

/**
 * The token data from the database of the given token
 */
export type TokenLookupResponse = {
  data: {
    [key: string]: TokenInfo;
  };
};

export type TokenInfo = {
  internalId: string;
  coingeckoId?: string | null;
  platforms: Platforms;
  isNative: boolean;
  name: string;
  symbol: string;
  scanResult?: ScanResult | null;
  scannedAt?: string | null;
  meta?: TokenMetadata | null;
};

/**
 * The token data from the database of the given token. The keys in priceInfo are the different currencies e.g: usd, aud
 */
export type TokenLookupWithPriceInfoResponse = {
  data: {
    [key: string]: {
      internalId: string;
      coingeckoId?: string | null;
      platforms: Platforms;
      isNative: boolean;
      name: string;
      symbol: string;
      scanResult?: ScanResult | null;
      scannedAt?: string | null;
      meta?: TokenMetadata | null;
      priceInfo: {
        [key: string]: {
          price: number | null;
          priceChange24h: number | null;
          priceChangePercent24h: number | null;
        };
      } | null;
    };
  };
};

/**
 * The response of the watchlist endpoint
 */
export type WatchlistResponse = {
  data: Array<{
    internalId: string;
    coingeckoId?: string | null;
    platforms: Platforms;
    isNative: boolean;
    name: string;
    symbol: string;
    scanResult?: ScanResult | null;
    scannedAt?: string | null;
    meta?: TokenMetadata | null;
    rank?: number | null;
  }>;
  metadata: MetaData;
};

/**
 * The meta data for queries
 */
export type MetaData = {
  currentPage: number;
  totalPages: number;
  totalRecords: number;
};

/**
 * Detailed price info about the different tokens
 */
export type ByCurrencyMetaInfo = Array<{
  internalId: string;
  coingeckoId?: string | null;
  platforms: Platforms;
  isNative: boolean;
  name: string;
  symbol: string;
  scanResult?: ScanResult | null;
  scannedAt?: string | null;
  meta?: TokenMetadata | null;
  id: string | null;
  image: string | null;
  current_price?: number | null;
  market_cap?: number | null;
  market_cap_rank?: number | null;
  fully_diluted_valuation?: number | null;
  total_volume?: number | null;
  high_24h?: number | null;
  low_24h?: number | null;
  price_change_24h?: number | null;
  price_change_percentage_24h?: number | null;
  market_cap_change_24h?: number | null;
  market_cap_change_percentage_24h?: number | null;
  circulating_supply?: number | null;
  total_supply?: number | null;
  max_supply?: number | null;
  ath?: number | null;
  ath_change_percentage?: number | null;
  ath_date?: string | null;
  atl?: number | null;
  atl_change_percentage?: number | null;
  atl_date?: string | null;
  roi?: {
    times: number;
    currency: string;
    percentage: number;
  } | null;
  last_updated?: string | null;
  sparkline_in_7d?: {
    price: Array<number> | null;
  } | null;
}>;

/**
 * The price info of the various tokens in a limited set of currencies
 */
export type CoinPriceResponse = {
  [key: string]: {
    [key: string]: {
      price?: number | null;
      change24?: number | null;
      vol24?: number | null;
      marketCap?: number | null;
    };
  };
};

/**
 * The token info that is returned by Birdeye
 */
export type BirdeyeTrendingResponse = Array<{
  internalId: string;
  coingeckoId?: string | null;
  platforms: Platforms;
  isNative: boolean;
  name: string;
  symbol: string;
  scanResult?: ScanResult | null;
  scannedAt?: string | null;
  meta?: TokenMetadata | null;
  decimals: number;
  liquidity: number;
  address: string;
  logoURI?: string | null;
  volume24hUSD?: number | null;
  volume24hChangePercent?: number | null;
  fdv?: number | null;
  marketcap?: number | null;
  rank?: number | null;
  price?: number | null;
  price24hChangePercent?: number | null;
  lastUpdated: string;
  website?: string | null;
  twitter?: string | null;
  discord?: string | null;
  medium?: string | null;
  verified?: boolean | null;
  sparkline: Array<{
    unixTime: number;
    value: number;
  }> | null;
}>;

export type GetV1TokenlistData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * A query param to indicate whether the Solana tokens should be returned as well
     */
    includeSolana?: string | boolean;
  };
  url: '/v1/tokenlist';
};

export type GetV1TokenlistResponses = {
  /**
   * Default Response
   */
  200: TokenListResponse;
};

export type GetV1TokenlistResponse =
  GetV1TokenlistResponses[keyof GetV1TokenlistResponses];

export type GetV1TokensData = {
  body?: never;
  path?: never;
  query: {
    /**
     * The caip2 ID of the chain we want to get back the tokens of
     */
    caip2Id: string;
  };
  url: '/v1/tokens';
};

export type GetV1TokensResponses = {
  /**
   * Default Response
   */
  200: TokensResponse;
};

export type GetV1TokensResponse =
  GetV1TokensResponses[keyof GetV1TokensResponses];

export type GetV1TrendingListData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * The caip2 ID of the network we want the trending list of
     */
    network?: string;
  };
  url: '/v1/trending-list';
};

export type GetV1TrendingListResponses = {
  /**
   * Default Response
   */
  200: TrendingListResponse;
};

export type GetV1TrendingListResponse =
  GetV1TrendingListResponses[keyof GetV1TrendingListResponses];

export type PostV1TokenLookupData = {
  body: {
    tokens: Array<Caip2IdAddressPair | InternalId>;
  };
  path?: never;
  query?: never;
  url: '/v1/token/lookup';
};

export type PostV1TokenLookupResponses = {
  /**
   * Default Response
   */
  200: TokenLookupResponse;
};

export type PostV1TokenLookupResponse =
  PostV1TokenLookupResponses[keyof PostV1TokenLookupResponses];

export type PostV1TokenLookupWithPriceData = {
  body: {
    tokens: Array<Caip2IdAddressPair | InternalId>;
  };
  path?: never;
  query?: never;
  url: '/v1/token/lookup-with-price';
};

export type PostV1TokenLookupWithPriceResponses = {
  /**
   * Default Response
   */
  200: TokenLookupWithPriceInfoResponse;
};

export type PostV1TokenLookupWithPriceResponse =
  PostV1TokenLookupWithPriceResponses[keyof PostV1TokenLookupWithPriceResponses];

export type GetV1WatchlistData = {
  body?: never;
  path?: never;
  query: {
    page: number;
    pageSize: number;
    excludePlatforms?: Array<string>;
  };
  url: '/v1/watchlist/';
};

export type GetV1WatchlistResponses = {
  /**
   * Default Response
   */
  200: WatchlistResponse;
};

export type GetV1WatchlistResponse =
  GetV1WatchlistResponses[keyof GetV1WatchlistResponses];

export type GetV1WatchlistMarketsData = {
  body?: never;
  path?: never;
  query: {
    /**
     * The available currencies: usd, eur, aud, cad, chf, clp, czk, dkk, gbp, hkd, huf, ils, inr
     */
    currency: Currency;
    topMarkets?: boolean;
  };
  url: '/v1/watchlist/markets';
};

export type GetV1WatchlistMarketsResponses = {
  /**
   * Default Response
   */
  200: ByCurrencyMetaInfo;
};

export type GetV1WatchlistMarketsResponse =
  GetV1WatchlistMarketsResponses[keyof GetV1WatchlistMarketsResponses];

export type GetV1WatchlistTokensData = {
  body?: never;
  path?: never;
  query: {
    /**
     * The available currencies: usd, eur, aud, cad, chf, clp, czk, dkk, gbp, hkd, huf, ils, inr
     */
    currency: Currency;
    caip2Id?: string;
    /**
     * A list of tokens delimited by coma
     */
    tokens?: string;
  };
  url: '/v1/watchlist/tokens';
};

export type GetV1WatchlistTokensResponses = {
  /**
   * Default Response
   */
  200: ByCurrencyMetaInfo;
};

export type GetV1WatchlistTokensResponse =
  GetV1WatchlistTokensResponses[keyof GetV1WatchlistTokensResponses];

export type GetV1WatchlistPriceData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/v1/watchlist/price';
};

export type GetV1WatchlistPriceResponses = {
  /**
   * Default Response
   */
  200: CoinPriceResponse;
};

export type GetV1WatchlistPriceResponse =
  GetV1WatchlistPriceResponses[keyof GetV1WatchlistPriceResponses];

export type GetV1WatchlistTrendingData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Either the "name" or the caip2 ID
     */
    network?: string;
  };
  url: '/v1/watchlist/trending';
};

export type GetV1WatchlistTrendingResponses = {
  /**
   * Default Response
   */
  200: BirdeyeTrendingResponse;
};

export type GetV1WatchlistTrendingResponse =
  GetV1WatchlistTrendingResponses[keyof GetV1WatchlistTrendingResponses];
