// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'https://core-profile-api.avax.network' | (string & {});
};

/**
 * Get addresses request body
 *
 * Request body for the get addresses with activity endpoint
 */
export type GetAddressesRequestBody = {
  networkType: NetworkType;
  /**
   * The extended public key that matches the provided network type.
   */
  extendedPublicKey: string & string;
  /**
   * Whether the addresses should be calculated for testnet.
   */
  isTestnet?: boolean;
  /**
   * Whether the response should only include addresses with activity.
   */
  onlyWithActivity?: boolean;
  /**
   * Whether the response should include 20 extra external addresses after the last index with activity.
   */
  withExtraAddresses?: boolean;
};

/**
 * The network (VM) type of the addresses to be retrieved.
 */
export type NetworkType = 'AVM' | 'PVM';

/**
 * Get addresses response
 *
 * Response for the get addresses with activity endpoint
 */
export type GetAddressesResponse = {
  networkType: NetworkType;
  /**
   * The external addresses of the wallet.
   */
  externalAddresses: Array<AddressItem>;
  /**
   * The internal (change) addresses of the wallet.
   */
  internalAddresses: Array<AddressItem>;
};

/**
 * The address and its index in the given wallet
 */
export type AddressItem = {
  address: string;
  index: number;
  hasActivity: boolean;
};

export type PostV1GetAddressesData = {
  /**
   * Request body for the get addresses with activity endpoint
   */
  body: GetAddressesRequestBody;
  path?: never;
  query?: never;
  url: '/v1/get-addresses';
};

export type PostV1GetAddressesResponses = {
  /**
   * Default Response
   */
  200: GetAddressesResponse;
};

export type PostV1GetAddressesResponse =
  PostV1GetAddressesResponses[keyof PostV1GetAddressesResponses];
