export enum BridgeEvents {
  BRIDGE_CONFIG_UPDATE_EVENT = 'BRIDGE_CONFIG_UPDATE_EVENT',
  BRIDGE_TRANSACTIONS_UPDATED = 'BRIDGE_TRANSACTIONS_UPDATED',
  BRIDGE_TRANSFER_EVENT = 'BRIDGE_TRANSFER_EVENT',
}
